import { ConnectButton } from "@rainbow-me/rainbowkit"
import type { NextPage } from "next"
import Head from "next/head"
import { Flex, Box, Text, Button } from "@chakra-ui/react"

import Card from "../theme/Card"
import Currency from "../components/Currency"
import { ArrowDownIcon } from "@chakra-ui/icons"
import Footer from "../components/Footer"

const Home: NextPage = () => {
  return (
    <>
      <Box
        background="url('bg2.jpg') center"
        backgroundSize="cover"
        minH="100vh"
        minW="100vw"
        position="absolute"
      >
        <Head>
          <title>RainbowKit App</title>
          <meta
            name="description"
            content="Generated by @rainbow-me/create-rainbowkit"
          />
          <link rel="icon" href="/favicon.ico" />
        </Head>

        <Flex justifyContent="space-between" m={3}>
          <img src="Full Logo.svg" width={200} />
          <ConnectButton />
        </Flex>

        <Box
          p={4}
          display="flex"
          justifyContent="center"
          alignContent="center"
          w="100vw"
          h="100vh"
          as="main"
        >
          <Card variant="primary" maxW="460" margin="auto">
            <Text fontWeight="bold" mb={2}>
              Swap
            </Text>

            <Currency />
            <Box
              borderRadius="md"
              background="white"
              padding=".25rem .5rem"
              m={2}
              display="inline-block"
            >
              <ArrowDownIcon />
            </Box>
            <Currency />

            <Button variant="primary" mt={4} size="lg" width="100%">
              Swap
            </Button>
          </Card>
        </Box>

        <Footer />
      </Box>
    </>
  )
}

export default Home
